const practiceTrials = [
  {
    id: "practice_1",
    phase: "practice",
    block_id: 0,
    trial_in_block: 1,
    condition: "practice",
    utterance: "The scissors",
    item: "scissors",
    image: "stimuli/practice_01.png",
    greyCell: "topLeft",
    correctAnswer: "topRight",
  },
  {
    id: "practice_2",
    phase: "practice",
    block_id: 0,
    trial_in_block: 2,
    condition: "practice",
    utterance: "The key",
    item: "key",
    image: "stimuli/practice_02.png",
    greyCell: "topLeft",
    correctAnswer: "bottomLeft",
  },
  {
    id: "practice_3",
    phase: "practice",
    block_id: 0,
    trial_in_block: 3,
    condition: "practice",
    utterance: "The ring",
    item: "ring",
    image: "stimuli/practice_03.png",
    greyCell: "topLeft",
    correctAnswer: "bottomLeft",
  },
  {
    id: "practice_4",
    phase: "practice",
    block_id: 0,
    trial_in_block: 4,
    condition: "practice",
    utterance: "The toothbrush",
    item: "toothbrush",
    image: "stimuli/practice_04.png",
    greyCell: "topLeft",
    correctAnswer: "bottomRight",
  },
  {
    id: "practice_5",
    phase: "practice",
    block_id: 0,
    trial_in_block: 5,
    condition: "practice",
    utterance: "The socks",
    item: "socks",
    image: "stimuli/practice_05.png",
    greyCell: "topLeft",
    correctAnswer: "topRight",
  }
];

export default practiceTrials;